version: '3.9'
services:
  php:
    image: btiisseem018/my-php-apache-app
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Ibtissam
      MYSQL_DATABASE: backend
